Revert "US3987 remove dependencies on jquery-migrate"
This reverts commit 620b20aeaa3141402d37e582f67182ff9603fef2.

Fixes error:

Error: Mismatched anonymous define() module: undefined
http://requirejs.org/docs/errors.html#mismatch